# Site settings
title: EAL hackathon May 2016
email: techevents@eal.dk
description: "EAL hackathon is an event organised by the EAL tech event team. We want to promote cool tech and make people meetup and work together to inspire and help each other"
#baseurl: ""
#url: "http://yourdomain.com"
#twitter_username: jekyllrb
#github_username:  jekyll
facebook_grouplink: groups/243909452640594
facebook_groupname: EAL Hackathon 2016

url: https://moozer.github.io
baseurl: /hackathon2016

# Build settings
markdown: kramdown
permalink: pretty
