# Site settings
title: EAL hackathon May 2016
email: mon@eal.dk
description: "EAL hackathon is an event organised by the EAL tech event team. We want to promote cool tech and make people meetup and work together to inspire and help each other"
baseurl: ""
#url: "http://yourdomain.com"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
